dict = {
	server_host: `Server Host`,
	server_host_submit: `Change`,
	logout: `Logout`,
	high_damage_numbers_patch: `High Damage Numbers Patch`,
	skip_mission_start_timer: `Skip Mission Start Timer`,
	simulacrum_blacklisted: `Blacklisted Enemies in Simulacrum`,
	simulacrum_whitelisted: `Whitelisted Enemies in Simulacrum`,
	pause_always_stops_time: `Pause Always Stops Time`,
	ee_log_in_console: `EE.log in Console`,
	fov_override: `FOV Override (0 = disabled)`,
	save_config: `Save changes to client_config.json`,

	camtype: `Camera Type`,
	gamecam: `Normal`,
	freecam: `Freecam`,
	lockcam: `Locked In Place`,
	pos: `Position`,
	tp_submit: `Teleport To`,
	custom: `Custom`,
	marker_obj: `Objective`,
	marker_target: `Target`,
	marker_surcap: `Life Support Capsule`,
	marker_surpup: `Life Support Pickup`,
	marker_a: `A`,
	marker_b: `B`,
	marker_c: `C`,
	marker_wp: `Waypoint`,
	marker_focus: `Focus`,
	marker_extract: `Extraction`,

	enable_auto_start: `Enable Auto Start`,
	disable_auto_start: `Disable Auto Start`,
	clear_script_log: `Clear Script Log`,
	console: `Console`,

	err: `Connection to DLL lost.`,
	err_retry: `Attempt to reconnect.`,
}