// French translation by Vitruvio (zexal.)
dict = {
	server_host: `Hôte (serveur)`,
	server_host_submit: `Modifier`,
	logout: `Déconnexion`,
	high_damage_numbers_patch: `Patch du cap de dégâts`,
	skip_mission_start_timer: `Passer le compte à rebours du début de mission`,
	simulacrum_blacklisted: `Liste noir des ennemis en Simulacre`,
	simulacrum_whitelisted: `Liste blanche des ennemis en Simulacre`,
	pause_always_stops_time: `Pause arrête le temps`,
	ee_log_in_console: `La console affiche le EE.log`,
	fov_override: `Override du champ de vision (0 = désactivé)`,
	save_config: `Sauvegarder les paramètres dans client_config.json`,

	camtype: `Type de caméra`,
	gamecam: `Normal`,
	freecam: `Caméra libre`,
	lockcam: `Caméra bloquée sur place`,
	pos: `Position`,
	tp_submit: `Se teleporter vers`,
	custom: `Personnalisé`,
	marker: `|TYPE| in |DIST|m`,
	marker_unk: `Marker`,
	marker_obj: `Objectif`,
	marker_target: `Cible`,
	marker_surcap: `Capsule de survie`,
	marker_surpup: `Module de survie`,
	marker_a: `A`,
	marker_b: `B`,
	marker_c: `C`,
	marker_wp: `Marqueur`,
	marker_focus: `Focus`,
	marker_extract: `Extraction`,

	enable_auto_start: `Activer le lancement auto`,
	disable_auto_start: `Désactiver le lancement auto`,
	clear_script_log: `Vider le log du script`,
	console: `Console`,

	err: `Connexion au DLL perdue.`,
	err_retry: `Tentative de reconnexion.`,
}