dict = {
	server_host: `服务器主机`,
	server_host_submit: `更改`,
	logout: `注销`,
	high_damage_numbers_patch: `高伤害数字补丁`,
	skip_mission_start_timer: `跳过任务倒计时`,
	simulacrum_blacklisted: `幻影装置的隐藏敌人`,
	simulacrum_whitelisted: `幻影装置的默认敌人`,
	pause_always_stops_time: `Esc暂停游戏`,
	ee_log_in_console: `在控制台输出EE.log`,
	fov_override: `视野重写 (0 = 关闭)`,
	save_config: `在client_config.json保存更改`,

	camtype: `镜头类型`,
	gamecam: `正常`,
	freecam: `自由视角`,
	lockcam: `原地锁定`,
	pos: `位置`,
	tp_submit: `传送至`,
	custom: `自定义`,
	marker: `|TYPE| 在 |DIST|米`,
	marker_unk: `通用标记点`,
	marker_obj: `标记目标`,
	marker_target: `目标`,
	marker_surcap: `大型生命维持胶囊`,
	marker_surpup: `小型生命维持胶囊`,
	marker_a: `A`,
	marker_b: `B`,
	marker_c: `C`,
	marker_wp: `标点`,
	marker_focus: `专精球`,
	marker_extract: `撤离点`,

	enable_auto_start: `开启自动启动`,
	disable_auto_start: `关闭自动启动`,
	clear_script_log: `清除脚本日志`,
	console: `控制台`,

	err: `与DLL连接丢失。`,
	err_retry: `尝试重连。`,
}